export const FETCH_USER = 'FETCH_USER';
export const FETCH_COURSE = 'FETCH_COURSE';
export const FETCH_PLANETS = 'FETCH_PLANETS';
export const FETCH_AUTH = 'FETCH_AUTH';
export const POST_COURSE_REQUEST = 'POST_COURSE_REQUEST';