export const FETCH_KEEPER_INFO = 'FETCH_KEEPER_INFO';
export const FETCH_KEEPER_CARD = 'FETCH_KEEPER_CARD';
export const FETCH_KEEPER_LIST = 'FETCH_KEEPER_LIST';
export const ACCEPT_OR_REJECT_COURSE = 'ACCEPT_OR_REJECT_COURSE';